version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pritom-network

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
    depends_on:
      - database
    networks:
      - pritom-network

  database:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_db=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pritom-network

volumes:
  pgdata:

networks:
  pritom-network:
    driver: bridge